name: Deploy Gulungus Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to AWS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ec2-user
        key: ${{ secrets.AWS_PRIVATE_KEY }}     
        script: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key 
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          echo "Testing SSH Connection..."
          cd ~/Gulungus-Bot
          ./deploy.sh
